export const LOGIN_ROLE_REQUEST = "LOGIN_ROLE_REQUEST";
export const LOGIN_ROLE_SUCCESS = "LOGIN_ROLE_SUCCESS";
export const LOGIN_ROLE_FAILURE = "LOGIN_ROLE_FAILURE";
export const LOGOUT = "LOGOUT";
