

// Janji Temu Types
export const CREATE_JANJI_TEMU_REQUEST = "CREATE_JANJI_TEMU_REQUEST";
export const CREATE_JANJI_TEMU_SUCCESS = "CREATE_JANJI_TEMU_SUCCESS";
export const CREATE_JANJI_TEMU_FAIL = "CREATE_JANJI_TEMU_FAIL";

export const GET_JANJI_TEMU_REQUEST = "GET_JANJI_TEMU_REQUEST";
export const GET_JANJI_TEMU_SUCCESS = "GET_JANJI_TEMU_SUCCESS";
export const GET_JANJI_TEMU_FAIL = "GET_JANJI_TEMU_FAIL";

export const UPDATE_JANJI_TEMU_REQUEST = "UPDATE_JANJI_TEMU_REQUEST";
export const UPDATE_JANJI_TEMU_SUCCESS = "UPDATE_JANJI_TEMU_SUCCESS";
export const UPDATE_JANJI_TEMU_FAIL = "UPDATE_JANJI_TEMU_FAIL";

export const DELETE_JANJI_TEMU_REQUEST = "DELETE_JANJI_TEMU_REQUEST";
export const DELETE_JANJI_TEMU_SUCCESS = "DELETE_JANJI_TEMU_SUCCESS";
export const DELETE_JANJI_TEMU_FAIL = "DELETE_JANJI_TEMU_FAIL";
